name: validate-lint-prettier

on:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies frontend
        run: npm ci

      - name: run prettier
        run: npm run prettier-check

      - name: run lint
        run: npm run lint
